# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cnc_pb2 as cnc__pb2


class GatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadPhotos = channel.unary_unary(
                '/cnc.Gateway/UploadPhotos',
                request_serializer=cnc__pb2.UploadPhotosRequest.SerializeToString,
                response_deserializer=cnc__pb2.UploadPhotosResponse.FromString,
                )
        self.GetArtifacts = channel.unary_unary(
                '/cnc.Gateway/GetArtifacts',
                request_serializer=cnc__pb2.GetArtifactsRequest.SerializeToString,
                response_deserializer=cnc__pb2.GetArtifactsResponse.FromString,
                )
        self.ModelToUnfold = channel.stream_unary(
                '/cnc.Gateway/ModelToUnfold',
                request_serializer=cnc__pb2.ModelChunk.SerializeToString,
                response_deserializer=cnc__pb2.UploadPhotosResponse.FromString,
                )


class GatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadPhotos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelToUnfold(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadPhotos': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPhotos,
                    request_deserializer=cnc__pb2.UploadPhotosRequest.FromString,
                    response_serializer=cnc__pb2.UploadPhotosResponse.SerializeToString,
            ),
            'GetArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifacts,
                    request_deserializer=cnc__pb2.GetArtifactsRequest.FromString,
                    response_serializer=cnc__pb2.GetArtifactsResponse.SerializeToString,
            ),
            'ModelToUnfold': grpc.stream_unary_rpc_method_handler(
                    servicer.ModelToUnfold,
                    request_deserializer=cnc__pb2.ModelChunk.FromString,
                    response_serializer=cnc__pb2.UploadPhotosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cnc.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadPhotos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cnc.Gateway/UploadPhotos',
            cnc__pb2.UploadPhotosRequest.SerializeToString,
            cnc__pb2.UploadPhotosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cnc.Gateway/GetArtifacts',
            cnc__pb2.GetArtifactsRequest.SerializeToString,
            cnc__pb2.GetArtifactsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModelToUnfold(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/cnc.Gateway/ModelToUnfold',
            cnc__pb2.ModelChunk.SerializeToString,
            cnc__pb2.UploadPhotosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
