# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cnc.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcnc.proto\x12\x03\x63nc\"(\n\tDimension\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"5\n\x05Photo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04view\x18\x03 \x01(\t\"i\n\x13UploadPhotosRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x1a\n\x06photos\x18\x02 \x03(\x0b\x32\n.cnc.Photo\x12\"\n\ndimensions\x18\x03 \x03(\x0b\x32\x0e.cnc.Dimension\"6\n\x14UploadPhotosResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"(\n\x0b\x41rtifactRef\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"%\n\x13GetArtifactsRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\";\n\x14GetArtifactsResponse\x12#\n\tartifacts\x18\x01 \x03(\x0b\x32\x10.cnc.ArtifactRef\"\x1a\n\nModelChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xd2\x01\n\x07Gateway\x12\x43\n\x0cUploadPhotos\x12\x18.cnc.UploadPhotosRequest\x1a\x19.cnc.UploadPhotosResponse\x12\x43\n\x0cGetArtifacts\x12\x18.cnc.GetArtifactsRequest\x1a\x19.cnc.GetArtifactsResponse\x12=\n\rModelToUnfold\x12\x0f.cnc.ModelChunk\x1a\x19.cnc.UploadPhotosResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cnc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DIMENSION']._serialized_start=18
  _globals['_DIMENSION']._serialized_end=58
  _globals['_PHOTO']._serialized_start=60
  _globals['_PHOTO']._serialized_end=113
  _globals['_UPLOADPHOTOSREQUEST']._serialized_start=115
  _globals['_UPLOADPHOTOSREQUEST']._serialized_end=220
  _globals['_UPLOADPHOTOSRESPONSE']._serialized_start=222
  _globals['_UPLOADPHOTOSRESPONSE']._serialized_end=276
  _globals['_ARTIFACTREF']._serialized_start=278
  _globals['_ARTIFACTREF']._serialized_end=318
  _globals['_GETARTIFACTSREQUEST']._serialized_start=320
  _globals['_GETARTIFACTSREQUEST']._serialized_end=357
  _globals['_GETARTIFACTSRESPONSE']._serialized_start=359
  _globals['_GETARTIFACTSRESPONSE']._serialized_end=418
  _globals['_MODELCHUNK']._serialized_start=420
  _globals['_MODELCHUNK']._serialized_end=446
  _globals['_GATEWAY']._serialized_start=449
  _globals['_GATEWAY']._serialized_end=659
# @@protoc_insertion_point(module_scope)
